name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    name: Lint & Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Sync all dependencies (prod + dev)
        run: uv sync --extra dev

      - name: Run Ruff
        run: uv run ruff check .

      - name: Run pytest
        run: uv run pytest

  docs:
    name: Build & Upload Docs
    needs: lint-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    concurrency:
      group: docs-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up uv
        uses: astral-sh/setup-uv@v1

      - name: Cache uv
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: uv-cache-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}

      - name: Sync all dependencies (prod + dev)
        run: uv sync --extra dev

      - name: Build MkDocs site
        run: uv run mkdocs build --strict

      - name: Upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: mkdocs-site
          path: site/
