name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
 
  publish-docs:
    name: Build and Deploy Docs to GitHub Pages
    runs-on: ubuntu-latest

       steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-cache-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}

      - name: Sync all dependencies (prod + dev)
        run: uv sync --extra dev

      - name: Build MkDocs site
        run: uv run mkdocs build --strict
        
  publish-pypi:
    name: Publish Package to PyPI
    runs-on: ubuntu-latest
    needs: publish-docs

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Sync only production dependencies
        run: uv sync --no-dev

      - name: Build package
        run: uv build --sdist --wheel --outdir dist/

      - name: Check distributions
        run: |
          ls -l dist/
          twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verbose: true
