name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-docs:
    name: Deploy Docs to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: mkdocs-site
          path: site/

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

  publish-pypi:
    name: Publish Package to PyPI
    runs-on: ubuntu-latest
    needs: publish-docs

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v1

      - name: Cache uv
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: uv-cache-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Sync only production dependencies
        run: uv sync --no-dev

      - name: Build package
        run: uv build --sdist --wheel --outdir dist/

      - name: Check distributions
        run: |
          ls -l dist/
          twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verbose: true
