name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # Matches version tags like v1.2.3

permissions:
  contents: read
  id-token: write  # Required for OIDC authentication

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # This ensures all tags are fetched

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Check directory contents
      run: |
        pwd
        ls -la

    - name: Build package
      run: python -m build --sdist --wheel --outdir dist/

    - name: List built distributions
      run: ls -l dist/

    - name: Check the built package
      run: twine check dist/*

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
        verbose: true